language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
before_install:
  - sudo add-apt-repository ppa:nijel/ppa -y
  - sudo apt-get update
  - sudo apt-get install libgammu-dev libdbd-sqlite3
install:
  - pip install -r requirements.txt
script:
  - CFLAGS="-Wall -Wextra" ./setup.py build
  - coverage run --source=. ./setup.py test
after_script:
  - coveralls
  - ocular --data-file ".coverage" --config-file ".coveragerc"
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
matrix:
  allow_failures:
    - python: "pypy"
    - python: "pypy3"
addons:
  coverity_scan:
    project:
      name: "gammu/python-gammu"
      description: "Build submitted via Travis CI"
    notification_email: michal@cihar.com
    build_command: ./setup.py build
    branch_pattern: coverity_scan
