language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - sudo add-apt-repository ppa:nijel/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install libgammu-dev
install:
  - pip install -r requirements.txt
script:
  - ./setup.py test
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
matrix:
  allow_failures:
    - python: "3.2"
    - python: "3.3"
